language: node_js

node_js:
  - '13'
env:
  global:
    secure: ThXspnUUTkdu+XObpRQ3pElFwTL0xHmtuvNbQULGqJbfjLoi8M9kG14C5O92ngLAY7EsLAAedlklTUlgEDRJJBd9VAJtB+7lTNy6cDYyge13K0pSqCKGVw8px5HefNAXrBsiB17/IeIee4INcEJCRftC8kjR8UUohJexCQhFFVc6sMNLAnyCeQVjEQliDMF3a1rFUXPIkx+1Oxf1B9SLeug811pi+YKwpyQV/Uc5MOBEPUFWDYkHDoBjbPdiQocEbgChIQVqoXnjRaWD1Hg9Wxid8Rh4/lVxAhu/l2pEZtO5JcRF4/0kvBlEOt6TyCdraPClmw9TxIFFjZg4NUjkfgCUYO4LV+ZPlsuviq0wBzavWeFiGtynUT1abJkzddxYycuFXvQDUJkujj9fwyBMx0BQb/ZW4yolMg8iPyEowI/ZbeoODWL58kMAlIEhj3SKHsPkfevsZM1uqntbqFKCAkx47zqBs5TsQGNyu2BctSCa8z1aAEmtpPrGDlMfyiu/SuaSCpTSW4Hh0ESl8JyQIqYocMt5QlBgqzzBTrxXGLMBrUjUcbeK941ycuZaVaLb0ZksY00XG970rRBF0qDNtZdMv4/ql25hd9fvxRjrhTozSt2WxCRqT53MHq3VSSiVY6YSDmLvD6mIzD3UIAWdSp212g2etC0lBTrMGyvNxhI=

after_success: npm run coverage
