name: ci

on:
  push:
    branches:
      - "**"

  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14, 16, 18]

    steps:
      - uses: actions/checkout@v3

      - name: Set up pnpm@v7.3.0
        uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.3.0

      - name: Set up node@v16
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: "pnpm"

      - run: pnpm install
      - run: pnpm run test

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
